# Generated by Django 5.2.6 on 2025-09-12 09:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0002_auto_20250907_1950"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_name",
                    models.CharField(max_length=50, verbose_name="等级名称"),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="最低薪资",
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="最高薪资",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "薪资等级",
                "verbose_name_plural": "薪资等级",
                "db_table": "t_salary_grade",
                "ordering": ["min_salary"],
            },
        ),
        migrations.CreateModel(
            name="SalaryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("PROMOTION", "晋升调薪"),
                            ("ANNUAL", "年度调薪"),
                            ("PERFORMANCE", "绩效调薪"),
                            ("MARKET", "市场调薪"),
                            ("OTHER", "其他调薪"),
                        ],
                        max_length=20,
                        verbose_name="调薪类型",
                    ),
                ),
                (
                    "old_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="调整前工资",
                    ),
                ),
                (
                    "new_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="调整后工资",
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="调整金额"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                ("reason", models.TextField(blank=True, verbose_name="调薪原因")),
                (
                    "approver_id",
                    models.IntegerField(blank=True, null=True, verbose_name="审批人ID"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_adjustments",
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "工资调整记录",
                "verbose_name_plural": "工资调整记录",
                "db_table": "t_salary_adjustment",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_month", models.DateField(verbose_name="工资月份")),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="基本工资",
                    ),
                ),
                (
                    "performance_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="绩效工资",
                    ),
                ),
                (
                    "allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="津贴补贴",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="奖金",
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="加班费",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="应发工资",
                    ),
                ),
                (
                    "social_insurance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="社会保险",
                    ),
                ),
                (
                    "housing_fund",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="住房公积金",
                    ),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="个人所得税",
                    ),
                ),
                (
                    "other_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="其他扣款",
                    ),
                ),
                (
                    "total_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="扣款合计",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="实发工资",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("CALCULATED", "已计算"),
                            ("APPROVED", "已审批"),
                            ("PAID", "已发放"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "pay_date",
                    models.DateField(blank=True, null=True, verbose_name="发放日期"),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="银行账号"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_salaries",
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "月度工资记录",
                "verbose_name_plural": "月度工资记录",
                "db_table": "t_monthly_salary",
                "ordering": ["-salary_month", "employee__name"],
                "unique_together": {("employee", "salary_month")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="基本工资",
                    ),
                ),
                (
                    "performance_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="绩效工资",
                    ),
                ),
                (
                    "allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="津贴补贴",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_configs",
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
                (
                    "salary_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salary_management.salarygrade",
                        verbose_name="薪资等级",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工薪资配置",
                "verbose_name_plural": "员工薪资配置",
                "db_table": "t_employee_salary_config",
                "ordering": ["-effective_date"],
                "unique_together": {("employee", "effective_date")},
            },
        ),
    ]
