# Generated by Django 5.2.6 on 2025-09-13 07:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingFundRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_name", models.CharField(max_length=50, verbose_name="费率名称")),
                (
                    "employee_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="个人缴费比例",
                    ),
                ),
                (
                    "employer_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="单位缴费比例",
                    ),
                ),
                (
                    "min_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="最低缴费基数",
                    ),
                ),
                (
                    "max_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="最高缴费基数",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "住房公积金费率配置",
                "verbose_name_plural": "住房公积金费率配置",
                "db_table": "t_housing_fund_rate",
                "ordering": ["-effective_date"],
            },
        ),
    ]
