# Generated by Django 5.2.6 on 2025-09-13 14:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0002_housingfundrate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HousingFundRate",
        ),
        migrations.AddField(
            model_name="employeesalaryconfig",
            name="housing_fund_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.12"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
                verbose_name="住房公积金缴费比例",
            ),
        ),
    ]
