# Generated by Django 5.2.6 on 2025-09-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0003_delete_housingfundrate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCalculationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="规则名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "standard_work_hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=8,
                        max_digits=4,
                        verbose_name="标准工作时长(小时/天)",
                    ),
                ),
                (
                    "standard_work_days_per_month",
                    models.IntegerField(default=22, verbose_name="标准工作天数(天/月)"),
                ),
                (
                    "personal_leave_deduction_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=5,
                        verbose_name="事假扣款比例(1.0=全扣)",
                    ),
                ),
                (
                    "sick_leave_deduction_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.5,
                        max_digits=5,
                        verbose_name="病假扣款比例",
                    ),
                ),
                (
                    "annual_leave_deduction_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=5,
                        verbose_name="年假扣款比例",
                    ),
                ),
                (
                    "weekday_overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=4,
                        verbose_name="工作日加班倍率",
                    ),
                ),
                (
                    "weekend_overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        max_digits=4,
                        verbose_name="周末加班倍率",
                    ),
                ),
                (
                    "holiday_overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        max_digits=4,
                        verbose_name="节假日加班倍率",
                    ),
                ),
                (
                    "late_deduction_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=6,
                        verbose_name="迟到扣款(元/分钟)",
                    ),
                ),
                (
                    "early_leave_deduction_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=6,
                        verbose_name="早退扣款(元/分钟)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "考勤计算规则",
                "verbose_name_plural": "考勤计算规则",
                "db_table": "t_attendance_calculation_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSalaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_work_days",
                    models.IntegerField(default=0, verbose_name="实际工作天数"),
                ),
                (
                    "actual_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="实际工作时长",
                    ),
                ),
                (
                    "personal_leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="事假时长(小时)",
                    ),
                ),
                (
                    "sick_leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="病假时长(小时)",
                    ),
                ),
                (
                    "annual_leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="年假时长(小时)",
                    ),
                ),
                (
                    "other_leave_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="其他假期时长(小时)",
                    ),
                ),
                (
                    "weekday_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="工作日加班时长(小时)",
                    ),
                ),
                (
                    "weekend_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="周末加班时长(小时)",
                    ),
                ),
                (
                    "holiday_overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="节假日加班时长(小时)",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="迟到分钟数"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, verbose_name="早退分钟数"),
                ),
                (
                    "missing_clock_days",
                    models.IntegerField(default=0, verbose_name="缺卡天数"),
                ),
                (
                    "normal_work_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="正常出勤工资",
                    ),
                ),
                (
                    "leave_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="请假扣款",
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="加班工资",
                    ),
                ),
                (
                    "late_early_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="迟到早退扣款",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "calculation_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="salary_management.attendancecalculationrule",
                        verbose_name="计算规则",
                    ),
                ),
                (
                    "monthly_salary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_detail",
                        to="salary_management.monthlysalary",
                        verbose_name="月度工资记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤薪资明细",
                "verbose_name_plural": "考勤薪资明细",
                "db_table": "t_attendance_salary_detail",
                "ordering": ["-created_at"],
            },
        ),
    ]
