# Generated by Django 5.2.6 on 2025-09-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_role_alter_user_options_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2025-09-15", verbose_name="创建时间"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.IntegerField(
                blank=True,
                help_text="与员工表的弱关联",
                null=True,
                verbose_name="关联员工ID",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("employee_id",)},
        ),
    ]
