# Generated by Django 5.2.6 on 2025-09-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginDate", models.DateField(verbose_name="培训开始时间")),
                ("endDate", models.DateField(verbose_name="培训结束时间")),
                (
                    "trainContent",
                    models.CharField(max_length=255, verbose_name="培训内容"),
                ),
                ("trainCost", models.FloatField(verbose_name="培训费用")),
                (
                    "personal",
                    models.ForeignKey(
                        db_column="personalId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.personal",
                        verbose_name="关联人员表",
                    ),
                ),
            ],
            options={
                "db_table": "t_train",
            },
        ),
    ]
