# Generated by Django 5.2.6 on 2025-09-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("station", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="员工姓名")),
                ("gender", models.IntegerField(verbose_name="性别(1:男，2:女)")),
                ("birthday", models.CharField(max_length=255, verbose_name="生日")),
                ("phone", models.CharField(max_length=255, verbose_name="电话号码")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("identity", models.CharField(max_length=255, verbose_name="身份证号")),
                ("education", models.IntegerField(verbose_name="学历")),
                ("school", models.CharField(max_length=255, verbose_name="毕业院校")),
                (
                    "beginDate",
                    models.CharField(max_length=255, verbose_name="入职日期"),
                ),
                ("workStatus", models.IntegerField(verbose_name="工作状态")),
                (
                    "station",
                    models.ForeignKey(
                        db_column="stationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="station.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工表",
                "db_table": "t_personal",
            },
        ),
    ]
