# Generated by Django 5.2.6 on 2025-09-07 11:50

from django.db import migrations


def create_initial_personal(apps, schema_editor):
    Station = apps.get_model('station', 'Station')
    Personal = apps.get_model('personal', 'Personal')
    
    # 获取岗位
    hr_manager = Station.objects.get(stationName='人力资源经理')
    recruiter = Station.objects.get(stationName='招聘专员')
    trainer = Station.objects.get(stationName='培训专员')
    tech_director = Station.objects.get(stationName='技术总监')
    senior_dev = Station.objects.get(stationName='高级开发工程师')
    junior_dev = Station.objects.get(stationName='初级开发工程师')
    tester = Station.objects.get(stationName='测试工程师')
    market_director = Station.objects.get(stationName='市场总监')
    sales_manager = Station.objects.get(stationName='销售经理')
    sales_specialist = Station.objects.get(stationName='销售专员')
    finance_manager = Station.objects.get(stationName='财务经理')
    accountant = Station.objects.get(stationName='会计')
    admin_manager = Station.objects.get(stationName='行政经理')
    admin_specialist = Station.objects.get(stationName='行政专员')
    
    employees = [
        {
            'name': '张三', 'gender': 1, 'birthday': '1985-03-15', 'phone': '13800138001',
            'age': 39, 'email': 'zhangsan@company.com', 'identity': '110101198503150001',
            'education': 3, 'school': '北京大学', 'beginDate': '2020-01-15', 'workStatus': 1,
            'station': hr_manager
        },
        {
            'name': '李四', 'gender': 2, 'birthday': '1990-07-20', 'phone': '13800138002',
            'age': 34, 'email': 'lisi@company.com', 'identity': '110101199007200002',
            'education': 2, 'school': '清华大学', 'beginDate': '2021-03-10', 'workStatus': 1,
            'station': recruiter
        },
        {
            'name': '王五', 'gender': 1, 'birthday': '1988-11-08', 'phone': '13800138003',
            'age': 36, 'email': 'wangwu@company.com', 'identity': '110101198811080003',
            'education': 3, 'school': '复旦大学', 'beginDate': '2019-08-20', 'workStatus': 1,
            'station': trainer
        },
        {
            'name': '赵六', 'gender': 1, 'birthday': '1982-05-12', 'phone': '13800138004',
            'age': 42, 'email': 'zhaoliu@company.com', 'identity': '110101198205120004',
            'education': 4, 'school': '上海交通大学', 'beginDate': '2018-06-01', 'workStatus': 1,
            'station': tech_director
        },
        {
            'name': '孙七', 'gender': 1, 'birthday': '1987-09-25', 'phone': '13800138005',
            'age': 37, 'email': 'sunqi@company.com', 'identity': '110101198709250005',
            'education': 3, 'school': '华中科技大学', 'beginDate': '2020-04-15', 'workStatus': 1,
            'station': senior_dev
        },
        {
            'name': '周八', 'gender': 2, 'birthday': '1992-12-03', 'phone': '13800138006',
            'age': 32, 'email': 'zhouba@company.com', 'identity': '110101199212030006',
            'education': 2, 'school': '西安电子科技大学', 'beginDate': '2022-01-10', 'workStatus': 1,
            'station': junior_dev
        },
        {
            'name': '吴九', 'gender': 1, 'birthday': '1989-04-18', 'phone': '13800138007',
            'age': 35, 'email': 'wujiu@company.com', 'identity': '110101198904180007',
            'education': 2, 'school': '大连理工大学', 'beginDate': '2021-07-01', 'workStatus': 1,
            'station': tester
        },
        {
            'name': '郑十', 'gender': 2, 'birthday': '1986-08-30', 'phone': '13800138008',
            'age': 38, 'email': 'zhengshi@company.com', 'identity': '110101198608300008',
            'education': 3, 'school': '中山大学', 'beginDate': '2019-11-20', 'workStatus': 1,
            'station': market_director
        },
        {
            'name': '钱十一', 'gender': 1, 'birthday': '1991-01-14', 'phone': '13800138009',
            'age': 33, 'email': 'qianshiyi@company.com', 'identity': '110101199101140009',
            'education': 2, 'school': '厦门大学', 'beginDate': '2021-09-15', 'workStatus': 1,
            'station': sales_manager
        },
        {
            'name': '陈十二', 'gender': 2, 'birthday': '1993-06-22', 'phone': '13800138010',
            'age': 31, 'email': 'chenshier@company.com', 'identity': '110101199306220010',
            'education': 2, 'school': '华南理工大学', 'beginDate': '2022-05-08', 'workStatus': 1,
            'station': sales_specialist
        },
        {
            'name': '刘十三', 'gender': 1, 'birthday': '1984-10-05', 'phone': '13800138011',
            'age': 40, 'email': 'liushisan@company.com', 'identity': '110101198410050011',
            'education': 3, 'school': '中南财经政法大学', 'beginDate': '2019-02-18', 'workStatus': 1,
            'station': finance_manager
        },
        {
            'name': '林十四', 'gender': 2, 'birthday': '1990-02-28', 'phone': '13800138012',
            'age': 34, 'email': 'linshisi@company.com', 'identity': '110101199002280012',
            'education': 2, 'school': '东北财经大学', 'beginDate': '2021-12-01', 'workStatus': 1,
            'station': accountant
        },
        {
            'name': '黄十五', 'gender': 1, 'birthday': '1987-07-11', 'phone': '13800138013',
            'age': 37, 'email': 'huangshiwu@company.com', 'identity': '110101198707110013',
            'education': 2, 'school': '南京大学', 'beginDate': '2020-10-12', 'workStatus': 1,
            'station': admin_manager
        },
        {
            'name': '杨十六', 'gender': 2, 'birthday': '1994-04-07', 'phone': '13800138014',
            'age': 30, 'email': 'yangshiliu@company.com', 'identity': '110101199404070014',
            'education': 1, 'school': '山东大学', 'beginDate': '2023-03-20', 'workStatus': 1,
            'station': admin_specialist
        },
    ]
    
    for emp_data in employees:
        Personal.objects.create(**emp_data)


def reverse_initial_personal(apps, schema_editor):
    Personal = apps.get_model('personal', 'Personal')
    Personal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
        ("station", "0002_auto_20250907_1950"),
    ]

    operations = [
        migrations.RunPython(create_initial_personal, reverse_initial_personal),
    ]
