# Generated by Django 5.2.6 on 2025-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_auto_20250907_1950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="education",
            field=models.IntegerField(
                choices=[
                    (1, "小学"),
                    (2, "初中"),
                    (3, "高中"),
                    (4, "中专"),
                    (5, "大专"),
                    (6, "本科"),
                    (7, "硕士"),
                    (8, "博士"),
                ],
                verbose_name="学历",
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "男"), (2, "女")], verbose_name="性别(1:男，2:女)"
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="workStatus",
            field=models.IntegerField(
                choices=[(1, "在职"), (2, "离职"), (3, "休假"), (4, "试用期")],
                verbose_name="工作状态",
            ),
        ),
    ]
