# Generated by Django 5.2.6 on 2025-09-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("needNum", models.IntegerField(verbose_name="招聘人数")),
                ("demand", models.CharField(max_length=255, verbose_name="招聘说明")),
                ("needEducation", models.IntegerField(verbose_name="所需学历")),
                ("startDate", models.DateField(verbose_name="开始时间")),
                ("endDate", models.DateField(verbose_name="结束时间")),
                ("recruitStatus", models.IntegerField(verbose_name="招聘状态")),
                (
                    "station",
                    models.ForeignKey(
                        db_column="stationId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="station.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘表",
                "db_table": "t_recruit",
            },
        ),
    ]
