# Generated by Django 5.2.6 on 2025-09-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stationName", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "department",
                    models.ForeignKey(
                        db_column="departmentId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
            ],
            options={
                "db_table": "t_station",
            },
        ),
    ]
