# Generated by Django 5.2.6 on 2025-09-07 11:50

from django.db import migrations


def create_initial_stations(apps, schema_editor):
    Department = apps.get_model('department', 'Department')
    Station = apps.get_model('station', 'Station')
    
    # 获取部门
    hr_dept = Department.objects.get(departmentName='人力资源部')
    tech_dept = Department.objects.get(departmentName='技术部')
    market_dept = Department.objects.get(departmentName='市场部')
    finance_dept = Department.objects.get(departmentName='财务部')
    admin_dept = Department.objects.get(departmentName='行政部')
    
    stations = [
        {'stationName': '人力资源经理', 'description': '负责人力资源部门管理工作', 'department': hr_dept},
        {'stationName': '招聘专员', 'description': '负责公司人员招聘工作', 'department': hr_dept},
        {'stationName': '培训专员', 'description': '负责员工培训和发展工作', 'department': hr_dept},
        
        {'stationName': '技术总监', 'description': '负责技术部门管理和技术决策', 'department': tech_dept},
        {'stationName': '高级开发工程师', 'description': '负责核心产品开发工作', 'department': tech_dept},
        {'stationName': '初级开发工程师', 'description': '负责基础开发工作', 'department': tech_dept},
        {'stationName': '测试工程师', 'description': '负责产品测试工作', 'department': tech_dept},
        
        {'stationName': '市场总监', 'description': '负责市场部门管理和市场策略', 'department': market_dept},
        {'stationName': '销售经理', 'description': '负责销售团队管理', 'department': market_dept},
        {'stationName': '销售专员', 'description': '负责客户开发和维护', 'department': market_dept},
        
        {'stationName': '财务经理', 'description': '负责财务部门管理工作', 'department': finance_dept},
        {'stationName': '会计', 'description': '负责日常会计核算工作', 'department': finance_dept},
        
        {'stationName': '行政经理', 'description': '负责行政部门管理工作', 'department': admin_dept},
        {'stationName': '行政专员', 'description': '负责日常行政事务', 'department': admin_dept},
    ]
    
    for station_data in stations:
        Station.objects.create(**station_data)


def reverse_initial_stations(apps, schema_editor):
    Station = apps.get_model('station', 'Station')
    Station.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
        ("department", "0002_auto_20250907_1949"),
    ]

    operations = [
        migrations.RunPython(create_initial_stations, reverse_initial_stations),
    ]
