# Generated by Django 5.2.6 on 2025-09-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0003_alter_personal_education_alter_personal_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clock_type",
                    models.CharField(
                        choices=[("IN", "上班"), ("OUT", "下班")],
                        max_length=10,
                        verbose_name="打卡类型",
                    ),
                ),
                ("clock_time", models.DateTimeField(verbose_name="打卡时间戳")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="打卡地点"
                    ),
                ),
                ("device", models.CharField(max_length=100, verbose_name="打卡设备")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "正常"),
                            ("LATE", "迟到"),
                            ("EARLY", "早退"),
                            ("MISSING", "缺卡"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="打卡状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡记录",
                "verbose_name_plural": "打卡记录管理",
                "db_table": "t_clock_in_record",
                "ordering": ["-clock_time"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "事假"),
                            ("SICK", "病假"),
                            ("ANNUAL", "年假"),
                            ("MATERNITY", "产假"),
                            ("PATERNITY", "陪产假"),
                            ("MARRIAGE", "婚假"),
                            ("FUNERAL", "丧假"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="请假类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="请假开始时间")),
                ("end_time", models.DateTimeField(verbose_name="请假结束时间")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="请假时长(小时)"
                    ),
                ),
                ("reason", models.TextField(verbose_name="请假原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已批准"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="personal.personal",
                        verbose_name="审批人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "请假记录",
                "verbose_name_plural": "请假记录管理",
                "db_table": "t_leave_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="加班开始时间")),
                ("end_time", models.DateTimeField(verbose_name="加班结束时间")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="加班时长(小时)"
                    ),
                ),
                ("reason", models.TextField(verbose_name="加班原因")),
                (
                    "overtime_type",
                    models.CharField(
                        choices=[
                            ("WEEKDAY", "工作日"),
                            ("WEEKEND", "周末"),
                            ("HOLIDAY", "节假日"),
                        ],
                        max_length=20,
                        verbose_name="加班类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已批准"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_overtimes",
                        to="personal.personal",
                        verbose_name="审批人",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "加班记录",
                "verbose_name_plural": "加班记录管理",
                "db_table": "t_overtime_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
