# Generated by Django 5.2.6 on 2025-09-13 13:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0002_auto_20250907_1950"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(max_length=100, verbose_name="规则名称"),
                ),
                (
                    "standard_work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=8,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="标准工作时长（小时）",
                    ),
                ),
                ("work_start_time", models.TimeField(verbose_name="标准上班时间")),
                ("work_end_time", models.TimeField(verbose_name="标准下班时间")),
                (
                    "late_tolerance_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="迟到容忍分钟数",
                    ),
                ),
                (
                    "early_leave_tolerance_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="早退容忍分钟数",
                    ),
                ),
                (
                    "overtime_threshold_minutes",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="加班认定阈值（分钟）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "考勤规则",
                "verbose_name_plural": "考勤规则",
                "db_table": "t_attendance_rule",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField(verbose_name="考勤日期")),
                (
                    "check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="签到时间"),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="签退时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "正常出勤"),
                            ("LATE", "迟到"),
                            ("EARLY_LEAVE", "早退"),
                            ("ABSENT", "缺勤"),
                            ("SICK_LEAVE", "病假"),
                            ("PERSONAL_LEAVE", "事假"),
                            ("ANNUAL_LEAVE", "年假"),
                            ("OVERTIME", "加班"),
                            ("BUSINESS_TRIP", "出差"),
                            ("WORK_FROM_HOME", "居家办公"),
                        ],
                        default="PRESENT",
                        max_length=20,
                        verbose_name="考勤状态",
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="工作时长（小时）",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="加班时长（小时）",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="迟到分钟数",
                    ),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="早退分钟数",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "is_holiday",
                    models.BooleanField(default=False, verbose_name="是否节假日"),
                ),
                (
                    "is_weekend",
                    models.BooleanField(default=False, verbose_name="是否周末"),
                ),
                (
                    "original_check_in_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="原始签到时间"
                    ),
                ),
                (
                    "original_check_out_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="原始签退时间"
                    ),
                ),
                (
                    "original_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRESENT", "正常出勤"),
                            ("LATE", "迟到"),
                            ("EARLY_LEAVE", "早退"),
                            ("ABSENT", "缺勤"),
                            ("SICK_LEAVE", "病假"),
                            ("PERSONAL_LEAVE", "事假"),
                            ("ANNUAL_LEAVE", "年假"),
                            ("OVERTIME", "加班"),
                            ("BUSINESS_TRIP", "出差"),
                            ("WORK_FROM_HOME", "居家办公"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="原始考勤状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
                (
                    "applied_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_records",
                        to="attendance.attendancerule",
                        verbose_name="应用的考勤规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
                "db_table": "t_attendance_record",
                "ordering": ["-attendance_date", "employee__name"],
                "indexes": [
                    models.Index(
                        fields=["employee", "attendance_date"],
                        name="t_attendanc_employe_6ff23a_idx",
                    ),
                    models.Index(
                        fields=["attendance_date"],
                        name="t_attendanc_attenda_3525ec_idx",
                    ),
                    models.Index(
                        fields=["status"], name="t_attendanc_status_318f94_idx"
                    ),
                ],
                "unique_together": {("employee", "attendance_date")},
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("SICK_LEAVE", "病假"),
                            ("PERSONAL_LEAVE", "事假"),
                            ("ANNUAL_LEAVE", "年假"),
                            ("MATERNITY_LEAVE", "产假"),
                            ("PATERNITY_LEAVE", "陪产假"),
                            ("MARRIAGE_LEAVE", "婚假"),
                            ("BEREAVEMENT_LEAVE", "丧假"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="请假类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "days_count",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="请假天数",
                    ),
                ),
                ("reason", models.TextField(verbose_name="请假原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已批准"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approver_id",
                    models.IntegerField(blank=True, null=True, verbose_name="审批人ID"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(blank=True, verbose_name="审批备注"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leave_attachments/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "请假申请",
                "verbose_name_plural": "请假申请",
                "db_table": "t_leave_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "start_date", "end_date"],
                        name="t_leave_app_employe_dba602_idx",
                    ),
                    models.Index(
                        fields=["status"], name="t_leave_app_status_e8fc07_idx"
                    ),
                    models.Index(
                        fields=["leave_type"], name="t_leave_app_leave_t_9d0ed5_idx"
                    ),
                ],
            },
        ),
    ]
