# Generated by Django 5.2.6 on 2025-09-13 12:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("personal", "0002_auto_20250907_1950"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("SICK_LEAVE", "病假"),
                            ("PERSONAL_LEAVE", "事假"),
                            ("ANNUAL_LEAVE", "年假"),
                            ("MATERNITY_LEAVE", "产假"),
                            ("PATERNITY_LEAVE", "陪产假"),
                            ("MARRIAGE_LEAVE", "婚假"),
                            ("BEREAVEMENT_LEAVE", "丧假"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="请假类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "days_count",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="请假天数",
                    ),
                ),
                ("reason", models.TextField(verbose_name="请假原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已批准"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approver_id",
                    models.IntegerField(blank=True, null=True, verbose_name="审批人ID"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "approval_remarks",
                    models.TextField(blank=True, verbose_name="审批备注"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leave_attachments/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="personal.personal",
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "请假申请",
                "verbose_name_plural": "请假申请",
                "db_table": "t_leave_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AttendanceDeductionRule",
        ),
        migrations.AlterModelOptions(
            name="attendancerule",
            options={
                "ordering": ["-effective_date"],
                "verbose_name": "考勤规则",
                "verbose_name_plural": "考勤规则",
            },
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="actual_work_hours",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="attendance_rule",
        ),
        migrations.RemoveField(
            model_name="attendancerule",
            name="break_duration",
        ),
        migrations.RemoveField(
            model_name="attendancerule",
            name="early_leave_tolerance",
        ),
        migrations.RemoveField(
            model_name="attendancerule",
            name="late_tolerance",
        ),
        migrations.RemoveField(
            model_name="attendancerule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="attendancerule",
            name="overtime_start_after",
        ),
        migrations.RemoveField(
            model_name="attendancerule",
            name="work_type",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="work_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="工作时长（小时）",
            ),
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="early_leave_tolerance_minutes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="早退容忍分钟数",
            ),
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="effective_date",
            field=models.DateField(default=2004, verbose_name="生效日期"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="late_tolerance_minutes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="迟到容忍分钟数",
            ),
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="overtime_threshold_minutes",
            field=models.IntegerField(
                default=30,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="加班认定阈值（分钟）",
            ),
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="rule_name",
            field=models.CharField(
                default="2025-09-12", max_length=100, verbose_name="规则名称"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendancerule",
            name="standard_work_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=8,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="标准工作时长（小时）",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance_date",
            field=models.DateField(verbose_name="考勤日期"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True, verbose_name="签到时间"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True, verbose_name="签退时间"),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="early_leave_minutes",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="早退分钟数",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="personal.personal",
                verbose_name="员工",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="late_minutes",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="迟到分钟数",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="remarks",
            field=models.TextField(
                blank=True, default=django.utils.timezone.now, verbose_name="备注"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "正常出勤"),
                    ("LATE", "迟到"),
                    ("EARLY_LEAVE", "早退"),
                    ("ABSENT", "缺勤"),
                    ("SICK_LEAVE", "病假"),
                    ("PERSONAL_LEAVE", "事假"),
                    ("ANNUAL_LEAVE", "年假"),
                    ("OVERTIME", "加班"),
                    ("BUSINESS_TRIP", "出差"),
                    ("WORK_FROM_HOME", "居家办公"),
                ],
                default="PRESENT",
                max_length=20,
                verbose_name="考勤状态",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerule",
            name="description",
            field=models.TextField(
                blank=True,
                default="leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<string>, line 1)",
                verbose_name="规则描述",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendancerule",
            name="work_end_time",
            field=models.TimeField(verbose_name="标准下班时间"),
        ),
        migrations.AlterField(
            model_name="attendancerule",
            name="work_start_time",
            field=models.TimeField(verbose_name="标准上班时间"),
        ),
        migrations.DeleteModel(
            name="AttendanceSummary",
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["employee", "start_date", "end_date"],
                name="t_leave_app_employe_dba602_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(fields=["status"], name="t_leave_app_status_e8fc07_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["leave_type"], name="t_leave_app_leave_t_9d0ed5_idx"
            ),
        ),
    ]
