# Generated by Django 5.2.6 on 2025-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departmentName", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "t_department",
            },
        ),
    ]
