# Generated by Django 5.2.6 on 2025-09-07 11:49

from django.db import migrations


def create_initial_departments(apps, schema_editor):
    Department = apps.get_model('department', 'Department')
    
    departments = [
        {'departmentName': '人力资源部', 'description': '负责公司人员招聘、培训、薪酬管理等工作'},
        {'departmentName': '技术部', 'description': '负责公司产品研发、技术支持等工作'},
        {'departmentName': '市场部', 'description': '负责公司市场推广、销售等工作'},
        {'departmentName': '财务部', 'description': '负责公司财务管理、会计核算等工作'},
        {'departmentName': '行政部', 'description': '负责公司行政管理、后勤保障等工作'},
    ]
    
    for dept_data in departments:
        Department.objects.create(**dept_data)


def reverse_initial_departments(apps, schema_editor):
    Department = apps.get_model('department', 'Department')
    Department.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_departments, reverse_initial_departments),
    ]
